services:
  - type: web
    name: creatorhub-backend
    runtime: node
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://your-vercel-app.vercel.app
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: creatorhub-db
    databaseName: creatorhub
    user: creatorhub
    plan: starter
